create table if not exists categories
(
	id bigint generated by default as identity,
	description varchar(255),
	name varchar(255) not null,
	primary key (id)
);

create table if not exists customers
(
	id bigint generated by default as identity,
	address varchar(255),
	name varchar(255),
	password varchar(255) not null,
	phone varchar(255),
	role varchar(255),
	username varchar(255) not null,
	primary key (id),
	constraint ukbepynu3b6l8k2ppuq6b33xfxc
		unique (username)
);

create table if not exists manufacturers
(
	id bigint generated by default as identity,
	country varchar(255),
	description varchar(255),
	name varchar(255) not null,
	primary key (id)
);

create table if not exists orders
(
	id bigint generated by default as identity,
	order_date timestamp(6) not null,
	status varchar(255),
	total_amount double precision not null,
	customer_id bigint not null,
	primary key (id),
	constraint fkpxtb8awmi0dk6smoh2vp1litg
		foreign key (customer_id) references customers
);

create table if not exists products
(
	id bigint generated by default as identity,
	description varchar(255),
	name varchar(255) not null,
	price double precision not null,
	category_id bigint,
	manufacturer_id bigint,
	primary key (id),
	constraint fkog2rp4qthbtt2lfyhfo32lsw9
		foreign key (category_id) references categories,
	constraint fkljnead8q1652k9q5p0fe0o1g2
		foreign key (manufacturer_id) references manufacturers,
	constraint products_price_check
		check (price >= (0)::double precision)
);

create table if not exists order_items
(
	id bigint generated by default as identity,
	price double precision not null,
	quantity integer not null,
	order_id bigint not null,
	product_id bigint not null,
	primary key (id),
	constraint fkbioxgbv59vetrxe0ejfubep1w
		foreign key (order_id) references orders,
	constraint fkocimc7dtr037rh4ls4l95nlfi
		foreign key (product_id) references products,
	constraint order_items_price_check
		check (price >= (0)::double precision),
	constraint order_items_quantity_check
		check (quantity >= 1)
);

create table if not exists reviews
(
	id bigint generated by default as identity,
	comment varchar(255) not null,
	created_at timestamp(6) not null,
	rating integer not null,
	customer_id bigint not null,
	product_id bigint not null,
	primary key (id),
	constraint fk4sm0k8kw740iyuex3vwwv1etu
		foreign key (customer_id) references customers,
	constraint fkpl51cejpw4gy5swfar8br9ngi
		foreign key (product_id) references products,
	constraint reviews_rating_check
		check ((rating <= 5) AND (rating >= 1))
);

create table if not exists stocks
(
	id bigint generated by default as identity,
	location varchar(255),
	quantity integer not null,
	product_id bigint not null,
	primary key (id),
	constraint fkff7be959jyco0iukc1dcjj9qm
		foreign key (product_id) references products,
	constraint stocks_quantity_check
		check (quantity >= 0)
);

