services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U myuser -d db_prod
      interval: 10s
      timeout: 3s
      retries: 3
  spring:
    image: spring
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
    db_data: